#logging:
#  level:
#    org.springframework.security: INFO

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#endpoints:
#  health:
#    sensitive: false
#    enabled: true
#  actuator:
#    enabled: true
#    sensitive: false
#  beans:
#    sensitive: false
#    enabled: true


management:
  security:
    enabled: false
#
feign:
  hystrix:
    enabled: false
##### Feign 配置
#feign:
#  # 是否开启断路器（熔断器）
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connect-timeout: 20000
#        read-timeout: 20000
#
